import { MigrationInterface, QueryRunner } from "typeorm";

export class Migration1707776526117 implements MigrationInterface {
    name = 'Migration1707776526117'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "eventos" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "status_id" integer NOT NULL, "tipo_id" integer NOT NULL, "titulo" character varying(80) NOT NULL, "palestrante" character varying(80), "endereco" character varying(250), "resumo" character varying(300) NOT NULL, "descricao" text NOT NULL, "data" date, "hora" TIME, "duracao" TIME, "is_publicado" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_40d4a3c6a4bfd24280cb97a509e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "pessoas_documentos" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "status_id" integer NOT NULL, "pessoa_id" integer NOT NULL, "tipo_id" integer NOT NULL, "numero" character varying(30) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_5c29f4623c5d485b6feda02ce8a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "regioes" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "status_id" integer NOT NULL, "nome" character varying(60) NOT NULL, "nome_alternativo" character varying(5) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_40ece6ca7676d9b86df959deae9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "cidades" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "status_id" integer NOT NULL, "estado_id" integer NOT NULL, "nome" character varying(60) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_cc606d4fea4335e32bd19f3a9fa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "estados" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "status_id" integer NOT NULL, "regiao_id" integer NOT NULL, "nome" character varying(60) NOT NULL, "nomeAlternativo" character varying(2) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_3d9a9f2658d5086012f27924d30" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "pessoas_enderecos" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "status_id" integer NOT NULL, "pessoa_id" integer NOT NULL, "estado_id" integer NOT NULL, "cidade_id" integer NOT NULL, "cep" character varying(8) NOT NULL, "pais" character varying(50) NOT NULL, "bairro" character varying(50) NOT NULL, "logradouro" character varying(50) NOT NULL, "numero" character varying(10), "complemento" character varying(50), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_f2166c12544354ceeda292e9400" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "pessoas_telefones" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "status_id" integer NOT NULL, "pessoa_id" integer NOT NULL, "tipo_id" integer NOT NULL, "numero" character varying(11) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_70649d91a0a9ffabe6d52744ea8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "pessoas_emails" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "pessoa_id" integer NOT NULL, "email" character varying(80) NOT NULL, "is_ativo" boolean NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_a8e5cb8f32f51af70527bc708d4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "pessoas_sites" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "pessoa_id" integer NOT NULL, "site" character varying(300) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_3f6e55fa2a1e97df460433964d1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "menus" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "status_id" integer NOT NULL, "nome" character varying(60) NOT NULL, "ordem" integer NOT NULL, "rota" character varying(100), "icone" character varying(100), "observacoes" character varying(100), "contexto_id" integer, "options" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_3fec3d93327f4538e0cbd4349c4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "menus_perfis" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "status_id" integer NOT NULL, "menu_id" integer NOT NULL, "perfil_id" integer, "observacoes" character varying(100), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_14b65894230428da33c3516a6f2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "perfis" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "status_id" integer NOT NULL, "nome" character varying(60) NOT NULL, "options" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_7502d953951e75abea461c12741" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "pessoas_perfis" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "status_id" integer NOT NULL, "pessoa_id" integer NOT NULL, "perfil_id" integer NOT NULL, "observacoes" character varying(50), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_8af29e60bc26deaf545a4c86933" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "pessoas_empresas" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "status_id" integer NOT NULL, "pessoa_id" integer NOT NULL, "empresa_id" integer NOT NULL, "observacoes" character varying(50), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_867f819555902bfab24576f94f0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "pessoas_senhas" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "status_id" integer NOT NULL, "pessoa_id" integer NOT NULL, "senha" character varying NOT NULL, "data_troca" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_1531972718c447c26696d188afc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "produtos_grupositens" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "produto_id" integer NOT NULL, "grupoitem_id" integer NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_d832ac5666e1ee6d3e77cba7bb6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "cotacoes_respostas_parcelas" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "resposta_id" integer NOT NULL, "prazo" integer NOT NULL, "valor" numeric(12,4) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_624a9b866d2e422c68de30b3708" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "cotacoes_respostas" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "cotacao_id" integer NOT NULL, "vendedor_id" integer NOT NULL, "fornecedor_id" integer NOT NULL, "forma_pagamento_id" integer NOT NULL, "frete_id" integer NOT NULL, "valor_frete" numeric(8,2), "numero_parcelas" integer NOT NULL, "prazo0" integer NOT NULL, "prazo_n" integer, "observacoes" character varying(500), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_2b17421414e8e65675a03759b0e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "pedidos_itens" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "status_id" integer NOT NULL, "pedido_id" integer NOT NULL, "produto_id" integer NOT NULL, "finalidade_id" integer NOT NULL, "data_necessidade" TIMESTAMP WITH TIME ZONE, "quantidade" numeric(4,12) NOT NULL, "largura" numeric(4,12), "altura" numeric(4,12), "comprimento" numeric(4,12), "peso" numeric(4,12), "ncm" character varying(8) NOT NULL, "prazo_entrega" integer NOT NULL, "garantia" character varying(30), "pis" numeric(4,12), "cofins" numeric(4,12), "icms" numeric(4,12), "ipi" numeric(4,12), "iss" numeric(4,12), "valor_liquido" numeric(2,12) NOT NULL, "valor_bruto" numeric(2,12) NOT NULL, "desconto" numeric(2,5) NOT NULL, "observacoes" character varying(500), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_64a3184c16f596af092d76bc371" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "pedidos_parcelas" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "pedido_id" integer NOT NULL, "prazo" integer NOT NULL, "valor" numeric(12,4) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_1021b5e52b35e72d8caa4ffa165" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "pedidos" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "status_id" integer NOT NULL, "tipo_id" integer NOT NULL, "cotacao_id" integer NOT NULL, "prioridade_id" integer NOT NULL, "cliente_id" integer NOT NULL, "fornecedor_id" integer NOT NULL, "vendedor_id" integer NOT NULL, "comprador_id" integer NOT NULL, "gerente_id" integer NOT NULL, "aprovador_id" integer NOT NULL, "forma_pagamento_id" integer NOT NULL, "frete_id" integer NOT NULL, "valor_frete" numeric(2,8), "numero_parcela" integer, "prazo0" integer, "prazon" integer, "data" TIMESTAMP WITH TIME ZONE NOT NULL, "data_envio" TIMESTAMP WITH TIME ZONE, "data_atendimento" TIMESTAMP WITH TIME ZONE, "centro_custo" character varying(30), "valor_total" numeric(2,12), "endereco_entrega" character varying(150), "endereco_cobranca" character varying(150), "observacoes" character varying(500), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_ebb5680ed29a24efdc586846725" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "cotacoes" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "status_id" integer NOT NULL, "tipo_id" integer NOT NULL, "prioridade_id" integer NOT NULL, "empresa_id" integer NOT NULL, "comprador_id" integer, "solicitante_id" integer NOT NULL, "aprovador_id" integer, "nome" character varying(30) NOT NULL, "data" date NOT NULL, "endereco_entrega" character varying(300), "endereco_cobranca" character varying(300), "centro_custo" character varying(50) NOT NULL, "valor_total" numeric(12,4), "regioes" jsonb, "data_encaminhada" TIMESTAMP WITH TIME ZONE, "email_enviado" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_5bf611a523f8c37582a65a767c0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "cotacoes_itens_respostas" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "status_id" integer NOT NULL, "item_id" integer NOT NULL, "vendedor_id" integer NOT NULL, "fornecedor_id" integer NOT NULL, "largura" numeric(12,4), "altura" numeric(12,4), "comprimento" numeric(12,4), "peso" numeric(12,4), "ncm" character varying(8) NOT NULL, "prazo_entrega" integer NOT NULL, "garantia" character varying(30), "pis" numeric(5,2), "cofins" numeric(5,2), "icms" numeric(5,2), "ipi" numeric(5,2), "iss" numeric(5,2), "valor_liquido" numeric(12,4) NOT NULL, "valor_bruto" numeric(12,4) NOT NULL, "desconto" numeric(5,2), "observacoes" character varying(500), "data_resposta" TIMESTAMP WITH TIME ZONE, "is_escolhida" boolean, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_72229e6356634213f4cfd412607" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "cotacoes_itens" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "status_id" integer NOT NULL, "cotacao_id" integer NOT NULL, "produto_id" integer NOT NULL, "finalidade_id" integer NOT NULL, "data_necessidade" date, "quantidade" numeric(12,4) NOT NULL, "observacoes" character varying, "resposta_id" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_3773d73e90e488211942075bfdc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "produtos" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "status_id" integer NOT NULL, "tipo_id" integer NOT NULL, "empresa_id" integer NOT NULL, "unidade_medida_id" integer NOT NULL, "produto" character varying(250) NOT NULL, "marca" character varying(50), "modelo" character varying(50), "fabricante" character varying(50), "part_number" character varying(10), "ncm" character varying(10), "caracteristicas" text, "custo_ultima_compra" numeric(12,4), "observacoes" character varying(500), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_a5d976312809192261ed96174f3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "convites" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "status_id" integer NOT NULL, "pessoa_id" integer NOT NULL, "nome_empresa" character varying(100) NOT NULL, "documento_empresa" character varying(30) NOT NULL, "nome_contato" character varying(60) NOT NULL, "email_contato" character varying(100) NOT NULL, "celular_contato" character varying(11) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_56a248f8700f1843839de151869" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "notificacoes" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "status_id" integer NOT NULL, "titulo" character varying(100) NOT NULL, "mensagem" character varying NOT NULL, "data" TIMESTAMP WITH TIME ZONE NOT NULL, "link" character varying(200) NOT NULL, "imagem" character varying(200) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_1161e00a97df46d9d3c5eed6545" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "notificacoes_usuarios" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "notificacao_id" integer NOT NULL, "pessoa_id" integer NOT NULL, "lida" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_d0105647420897f42c687a25781" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "pessoas" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "status_id" integer NOT NULL, "tipo_id" integer NOT NULL, "formato_juridico_id" integer, "regime_tributario_id" integer, "porte_id" integer, "nome" character varying(100) NOT NULL, "nome_alternativo" character varying(50), "data_nascimento" date, "is_fornecedor" boolean, "area_atuacao" character varying(100), "valor_diretor_aprova" numeric, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_fa8104cfc91dc207880a73a1acd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "pessoas_gruposItens" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "status_id" integer NOT NULL, "pessoa_id" integer NOT NULL, "grupoitem_id" integer NOT NULL, "observacoes" character varying(50), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_61883e5d52464ed7ceba848c824" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "grupos_itens" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "status_id" integer NOT NULL, "grupo_id" integer NOT NULL, "unidade_medida_id" integer NOT NULL, "nome" character varying(100) NOT NULL, "options" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_7a11c725149d74c5433a0acc61d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "grupos" ("id" integer NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "status_id" integer NOT NULL, "tipo_id" integer NOT NULL, "nome" character varying(100) NOT NULL, "nome_alternativo" character varying(100) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_34de64ec8a5ecd99afb23b2bd62" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "anexos" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "tipo_id" integer NOT NULL, "registro_id" integer NOT NULL, "key" character varying(800) NOT NULL, "mimetype" character varying(50) NOT NULL, "nome" character varying(200) NOT NULL, "size" integer NOT NULL, "url" character varying(300) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_da398d73b0fa1e7549520adc9f3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tipos_itens" ("id" integer NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "status_id" integer NOT NULL, "tipo_id" integer NOT NULL, "nome" character varying(60) NOT NULL, "nome_alternativo" character varying(60) NOT NULL, "codigo" character varying(20), "options" jsonb, "observacao" character varying(20), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_870f2637ba8ccb154834507683e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tipos" ("id" integer NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "status_id" integer NOT NULL, "nome" character varying(60) NOT NULL, "nome_alternativo" character varying(60) NOT NULL, "observacoes" character varying(100), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_9e292aa5abcebee247bc9193b55" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "artigos" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "status_id" integer NOT NULL, "titulo" character varying(50) NOT NULL, "autor" character varying(50) NOT NULL, "texto" text NOT NULL, "resumo" character varying(500) NOT NULL, "tags" character varying(200), "data_publicacao" date, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_713f961d8ef004dfae39de2dfaa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "status" ("id" integer NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "nome" character varying(30) NOT NULL, "nome_alternativo" character varying(3) NOT NULL, "options" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_e12743a7086ec826733f54e1d95" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "eventos" ADD CONSTRAINT "FK_46a0309574009ae28af91f37636" FOREIGN KEY ("status_id") REFERENCES "status"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "eventos" ADD CONSTRAINT "FK_789a59a9e2a08992a9b254e6014" FOREIGN KEY ("tipo_id") REFERENCES "tipos_itens"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pessoas_documentos" ADD CONSTRAINT "FK_e939f9735ce931a96cc07a4f7a5" FOREIGN KEY ("status_id") REFERENCES "status"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pessoas_documentos" ADD CONSTRAINT "FK_b33f3db9e3595ae5794bc84bc4a" FOREIGN KEY ("pessoa_id") REFERENCES "pessoas"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "pessoas_documentos" ADD CONSTRAINT "FK_29edfe7bdc144184d9d7b269d61" FOREIGN KEY ("tipo_id") REFERENCES "tipos_itens"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "regioes" ADD CONSTRAINT "FK_96248315e0216e821892da6f622" FOREIGN KEY ("status_id") REFERENCES "status"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cidades" ADD CONSTRAINT "FK_611ba55ce58e5a520cfc515169f" FOREIGN KEY ("status_id") REFERENCES "status"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cidades" ADD CONSTRAINT "FK_2e7d637be70af707d91216a1933" FOREIGN KEY ("estado_id") REFERENCES "estados"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "estados" ADD CONSTRAINT "FK_e8220b3fcc4dbddf7527705e576" FOREIGN KEY ("status_id") REFERENCES "status"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "estados" ADD CONSTRAINT "FK_96cad596c2475bddd1b438c16fb" FOREIGN KEY ("regiao_id") REFERENCES "regioes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pessoas_enderecos" ADD CONSTRAINT "FK_c79b8dbdc4ae436013fb73984d4" FOREIGN KEY ("status_id") REFERENCES "status"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pessoas_enderecos" ADD CONSTRAINT "FK_dc762ba53b91f0183500f6003e0" FOREIGN KEY ("pessoa_id") REFERENCES "pessoas"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "pessoas_enderecos" ADD CONSTRAINT "FK_ba9e3b79db386b895b2430f24bd" FOREIGN KEY ("estado_id") REFERENCES "estados"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pessoas_enderecos" ADD CONSTRAINT "FK_111a394d4702e247ca8982ef6c5" FOREIGN KEY ("cidade_id") REFERENCES "cidades"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pessoas_telefones" ADD CONSTRAINT "FK_70cee935d4a5ec80e63c8df680c" FOREIGN KEY ("status_id") REFERENCES "status"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pessoas_telefones" ADD CONSTRAINT "FK_15df92a33de336585e42ea9475a" FOREIGN KEY ("pessoa_id") REFERENCES "pessoas"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "pessoas_telefones" ADD CONSTRAINT "FK_6cae8173f2f12a61a8e05eab978" FOREIGN KEY ("tipo_id") REFERENCES "tipos_itens"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pessoas_emails" ADD CONSTRAINT "FK_856668b4cd963ce125d6cc6aee8" FOREIGN KEY ("pessoa_id") REFERENCES "pessoas"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "pessoas_sites" ADD CONSTRAINT "FK_bad59387fc1c3ada1273c938a82" FOREIGN KEY ("pessoa_id") REFERENCES "pessoas"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "menus" ADD CONSTRAINT "FK_14a0c59ecd0f07e8822ff0bb803" FOREIGN KEY ("status_id") REFERENCES "status"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "menus" ADD CONSTRAINT "FK_a9299eaf35545a824cef08810f7" FOREIGN KEY ("contexto_id") REFERENCES "tipos_itens"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "menus_perfis" ADD CONSTRAINT "FK_8e62593a05d8953e4c693d5ef00" FOREIGN KEY ("status_id") REFERENCES "status"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "menus_perfis" ADD CONSTRAINT "FK_09c2491bd9ce41c40545b6652a4" FOREIGN KEY ("menu_id") REFERENCES "menus"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "menus_perfis" ADD CONSTRAINT "FK_305025e18e469a7dca82ad4f833" FOREIGN KEY ("perfil_id") REFERENCES "perfis"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "perfis" ADD CONSTRAINT "FK_ba06560556c70175564bc2262db" FOREIGN KEY ("status_id") REFERENCES "status"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pessoas_perfis" ADD CONSTRAINT "FK_6667b206a341502927b2adcd5db" FOREIGN KEY ("status_id") REFERENCES "status"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pessoas_perfis" ADD CONSTRAINT "FK_2ff96a7b6faf812bb8be107fd2b" FOREIGN KEY ("pessoa_id") REFERENCES "pessoas"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "pessoas_perfis" ADD CONSTRAINT "FK_da5ec819085280f5ab722d36a3b" FOREIGN KEY ("perfil_id") REFERENCES "perfis"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pessoas_empresas" ADD CONSTRAINT "FK_809ae66ac48d993054d48e03619" FOREIGN KEY ("status_id") REFERENCES "status"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pessoas_empresas" ADD CONSTRAINT "FK_a88db58b1bab5a7a228867c06a9" FOREIGN KEY ("pessoa_id") REFERENCES "pessoas"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "pessoas_empresas" ADD CONSTRAINT "FK_67b1615978c3e5cea3b3c44c038" FOREIGN KEY ("empresa_id") REFERENCES "pessoas"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pessoas_senhas" ADD CONSTRAINT "FK_2c4b00947f27a72cb62320d0ee7" FOREIGN KEY ("status_id") REFERENCES "status"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pessoas_senhas" ADD CONSTRAINT "FK_2678f294df38daa9f2756f8f40e" FOREIGN KEY ("pessoa_id") REFERENCES "pessoas"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "produtos_grupositens" ADD CONSTRAINT "FK_1e464f40837ae3247e55cd8ee40" FOREIGN KEY ("produto_id") REFERENCES "produtos"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "produtos_grupositens" ADD CONSTRAINT "FK_50b4b62bba97280774e05bed17a" FOREIGN KEY ("grupoitem_id") REFERENCES "grupos_itens"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cotacoes_respostas_parcelas" ADD CONSTRAINT "FK_c18212ad09a8f6511273c0ebeb3" FOREIGN KEY ("resposta_id") REFERENCES "cotacoes_respostas"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "cotacoes_respostas" ADD CONSTRAINT "FK_460690825edeb8543e3918f2d8d" FOREIGN KEY ("cotacao_id") REFERENCES "cotacoes"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "cotacoes_respostas" ADD CONSTRAINT "FK_aba805afb0af8dbab83cc755a6b" FOREIGN KEY ("vendedor_id") REFERENCES "pessoas"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cotacoes_respostas" ADD CONSTRAINT "FK_7c527d2cbe405d77668b613f816" FOREIGN KEY ("fornecedor_id") REFERENCES "pessoas"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cotacoes_respostas" ADD CONSTRAINT "FK_3dc06ff0400db3d536dceafa901" FOREIGN KEY ("forma_pagamento_id") REFERENCES "tipos_itens"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cotacoes_respostas" ADD CONSTRAINT "FK_02cd42b7d9af5310d1d94fb03b7" FOREIGN KEY ("frete_id") REFERENCES "tipos_itens"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pedidos_itens" ADD CONSTRAINT "FK_33fe47da4aced52ceec02ff23c5" FOREIGN KEY ("status_id") REFERENCES "status"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pedidos_itens" ADD CONSTRAINT "FK_2f706fb8997d3e31261fefb653e" FOREIGN KEY ("pedido_id") REFERENCES "pedidos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pedidos_itens" ADD CONSTRAINT "FK_da85f71918d3494bf9594df4385" FOREIGN KEY ("produto_id") REFERENCES "produtos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pedidos_itens" ADD CONSTRAINT "FK_b2f99df3ce1597dceec33cb5e40" FOREIGN KEY ("finalidade_id") REFERENCES "tipos_itens"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pedidos_parcelas" ADD CONSTRAINT "FK_560fc6fd650396fd26dda2f6c53" FOREIGN KEY ("pedido_id") REFERENCES "pedidos"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "pedidos" ADD CONSTRAINT "FK_b45a63956a7594764773f78cb39" FOREIGN KEY ("status_id") REFERENCES "status"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pedidos" ADD CONSTRAINT "FK_fc027c56a080c8bb2e00e69923d" FOREIGN KEY ("tipo_id") REFERENCES "tipos_itens"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pedidos" ADD CONSTRAINT "FK_4818451165ddfea7dee91616b0d" FOREIGN KEY ("cotacao_id") REFERENCES "cotacoes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pedidos" ADD CONSTRAINT "FK_1f62699d31e9143363438136507" FOREIGN KEY ("prioridade_id") REFERENCES "tipos_itens"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pedidos" ADD CONSTRAINT "FK_2fc639de84f845569ac2c9f78aa" FOREIGN KEY ("cliente_id") REFERENCES "pessoas"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pedidos" ADD CONSTRAINT "FK_463ae49639acff27ec8c57f5c73" FOREIGN KEY ("fornecedor_id") REFERENCES "pessoas"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pedidos" ADD CONSTRAINT "FK_0db8bbade4d70d9b854cd21e8da" FOREIGN KEY ("vendedor_id") REFERENCES "pessoas"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pedidos" ADD CONSTRAINT "FK_2e54b204f572dd9cadc48f9fbde" FOREIGN KEY ("comprador_id") REFERENCES "pessoas"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pedidos" ADD CONSTRAINT "FK_3a22bd6118266e4492f522dc990" FOREIGN KEY ("gerente_id") REFERENCES "pessoas"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pedidos" ADD CONSTRAINT "FK_9a711eef9f3404f0d400ffcf17f" FOREIGN KEY ("aprovador_id") REFERENCES "pessoas"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pedidos" ADD CONSTRAINT "FK_5a6aebf7f18aaf59bc342c22fe1" FOREIGN KEY ("forma_pagamento_id") REFERENCES "tipos_itens"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pedidos" ADD CONSTRAINT "FK_11eee576e61da89cf70c92b262b" FOREIGN KEY ("frete_id") REFERENCES "tipos_itens"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cotacoes" ADD CONSTRAINT "FK_7e6f6b6f92c4c0798a769bd47bf" FOREIGN KEY ("status_id") REFERENCES "status"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cotacoes" ADD CONSTRAINT "FK_267259bd9339d126cd04b036a2c" FOREIGN KEY ("tipo_id") REFERENCES "tipos_itens"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cotacoes" ADD CONSTRAINT "FK_6c2941959b8a5efd0f450155d70" FOREIGN KEY ("prioridade_id") REFERENCES "tipos_itens"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cotacoes" ADD CONSTRAINT "FK_465e0759e2b62462b5998418e0a" FOREIGN KEY ("empresa_id") REFERENCES "pessoas"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cotacoes" ADD CONSTRAINT "FK_01268433833920f1f5f2ba81416" FOREIGN KEY ("comprador_id") REFERENCES "pessoas"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cotacoes" ADD CONSTRAINT "FK_6c0a49336f9ec8897fe1708e286" FOREIGN KEY ("solicitante_id") REFERENCES "pessoas"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cotacoes" ADD CONSTRAINT "FK_c6877b6157ba08b668c85b5ac97" FOREIGN KEY ("aprovador_id") REFERENCES "pessoas"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cotacoes_itens_respostas" ADD CONSTRAINT "FK_6e4ee75031b19bd7f89b4102c1c" FOREIGN KEY ("status_id") REFERENCES "status"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cotacoes_itens_respostas" ADD CONSTRAINT "FK_e38bfbe4d671010e25238656eb8" FOREIGN KEY ("item_id") REFERENCES "cotacoes_itens"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "cotacoes_itens_respostas" ADD CONSTRAINT "FK_6f13beb9426cbfc0ef8274d6520" FOREIGN KEY ("vendedor_id") REFERENCES "pessoas"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cotacoes_itens_respostas" ADD CONSTRAINT "FK_819a4ee774a78ee75be129eeab5" FOREIGN KEY ("fornecedor_id") REFERENCES "pessoas"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cotacoes_itens" ADD CONSTRAINT "FK_281e2dc2af30175924be6ea4804" FOREIGN KEY ("status_id") REFERENCES "status"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cotacoes_itens" ADD CONSTRAINT "FK_ae1ca98a176bb6305865bcfe38a" FOREIGN KEY ("cotacao_id") REFERENCES "cotacoes"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "cotacoes_itens" ADD CONSTRAINT "FK_4112991f9adb5bfce11a41be73a" FOREIGN KEY ("produto_id") REFERENCES "produtos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cotacoes_itens" ADD CONSTRAINT "FK_40ccc6ee4efabb23b8ebf2107ba" FOREIGN KEY ("finalidade_id") REFERENCES "tipos_itens"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "produtos" ADD CONSTRAINT "FK_0546b77e9b78f15ec796e9a19a0" FOREIGN KEY ("status_id") REFERENCES "status"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "produtos" ADD CONSTRAINT "FK_ff008aca54cdbfccdede506efb3" FOREIGN KEY ("tipo_id") REFERENCES "tipos_itens"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "produtos" ADD CONSTRAINT "FK_afe3324a3eebac3e0cdc0c3d6ff" FOREIGN KEY ("empresa_id") REFERENCES "pessoas"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "produtos" ADD CONSTRAINT "FK_89f6a0d2f5c0e9d9173b9eb955a" FOREIGN KEY ("unidade_medida_id") REFERENCES "tipos_itens"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "convites" ADD CONSTRAINT "FK_38b065a3191e800ab09ee95be8d" FOREIGN KEY ("status_id") REFERENCES "status"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "convites" ADD CONSTRAINT "FK_1673fcbe51386bcab8ec8a0fba1" FOREIGN KEY ("pessoa_id") REFERENCES "pessoas"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notificacoes" ADD CONSTRAINT "FK_10ec8f8dbe153d521b3b4521faf" FOREIGN KEY ("status_id") REFERENCES "status"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notificacoes_usuarios" ADD CONSTRAINT "FK_eb2e9c866126eefcb0f2890fc82" FOREIGN KEY ("notificacao_id") REFERENCES "notificacoes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notificacoes_usuarios" ADD CONSTRAINT "FK_335d31ebbefc95359a676c6d73a" FOREIGN KEY ("pessoa_id") REFERENCES "pessoas"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pessoas" ADD CONSTRAINT "FK_66f04e713618358aa6e14b86558" FOREIGN KEY ("status_id") REFERENCES "status"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pessoas" ADD CONSTRAINT "FK_e0aaffbb814e6626ca5cff60560" FOREIGN KEY ("tipo_id") REFERENCES "tipos_itens"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pessoas" ADD CONSTRAINT "FK_0ca7ffcf041c35b7bf80158a06b" FOREIGN KEY ("formato_juridico_id") REFERENCES "tipos_itens"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pessoas" ADD CONSTRAINT "FK_3298b8a7e21b647c78c4ade81b1" FOREIGN KEY ("regime_tributario_id") REFERENCES "tipos_itens"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pessoas" ADD CONSTRAINT "FK_f03548a8d1f8f5cf4d9047a54f6" FOREIGN KEY ("porte_id") REFERENCES "tipos_itens"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pessoas_gruposItens" ADD CONSTRAINT "FK_cb614ea80ab02c2d6723b2b3e47" FOREIGN KEY ("status_id") REFERENCES "status"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pessoas_gruposItens" ADD CONSTRAINT "FK_a60fbcb9bfb12864f6d4fcab008" FOREIGN KEY ("pessoa_id") REFERENCES "pessoas"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "pessoas_gruposItens" ADD CONSTRAINT "FK_4cdd6d219485acd8b9701d076b1" FOREIGN KEY ("grupoitem_id") REFERENCES "grupos_itens"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "grupos_itens" ADD CONSTRAINT "FK_b8322a1071ce9ca664dabc80dfa" FOREIGN KEY ("status_id") REFERENCES "status"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "grupos_itens" ADD CONSTRAINT "FK_2d6edcdcbb543eaed417415f618" FOREIGN KEY ("grupo_id") REFERENCES "grupos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "grupos_itens" ADD CONSTRAINT "FK_eef46445461f6da434c8f312cdb" FOREIGN KEY ("unidade_medida_id") REFERENCES "tipos_itens"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "grupos" ADD CONSTRAINT "FK_6278a731f5fc477dd038c8c7f86" FOREIGN KEY ("status_id") REFERENCES "status"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "grupos" ADD CONSTRAINT "FK_15bd1a4eb4ca6552bb6f3e8b248" FOREIGN KEY ("tipo_id") REFERENCES "tipos_itens"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "anexos" ADD CONSTRAINT "FK_58ad32cd81af0b2b21c6b2a927b" FOREIGN KEY ("tipo_id") REFERENCES "tipos_itens"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tipos_itens" ADD CONSTRAINT "FK_af2d543c00ded94c341b4c42a57" FOREIGN KEY ("status_id") REFERENCES "status"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tipos_itens" ADD CONSTRAINT "FK_1ff8a8dc5b95cb47d62a850d495" FOREIGN KEY ("tipo_id") REFERENCES "tipos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tipos" ADD CONSTRAINT "FK_96f9ebd3c8c3a39cddd83ec67d5" FOREIGN KEY ("status_id") REFERENCES "status"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "artigos" ADD CONSTRAINT "FK_dea7bfd0077a4519290399a131a" FOREIGN KEY ("status_id") REFERENCES "status"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "artigos" DROP CONSTRAINT "FK_dea7bfd0077a4519290399a131a"`);
        await queryRunner.query(`ALTER TABLE "tipos" DROP CONSTRAINT "FK_96f9ebd3c8c3a39cddd83ec67d5"`);
        await queryRunner.query(`ALTER TABLE "tipos_itens" DROP CONSTRAINT "FK_1ff8a8dc5b95cb47d62a850d495"`);
        await queryRunner.query(`ALTER TABLE "tipos_itens" DROP CONSTRAINT "FK_af2d543c00ded94c341b4c42a57"`);
        await queryRunner.query(`ALTER TABLE "anexos" DROP CONSTRAINT "FK_58ad32cd81af0b2b21c6b2a927b"`);
        await queryRunner.query(`ALTER TABLE "grupos" DROP CONSTRAINT "FK_15bd1a4eb4ca6552bb6f3e8b248"`);
        await queryRunner.query(`ALTER TABLE "grupos" DROP CONSTRAINT "FK_6278a731f5fc477dd038c8c7f86"`);
        await queryRunner.query(`ALTER TABLE "grupos_itens" DROP CONSTRAINT "FK_eef46445461f6da434c8f312cdb"`);
        await queryRunner.query(`ALTER TABLE "grupos_itens" DROP CONSTRAINT "FK_2d6edcdcbb543eaed417415f618"`);
        await queryRunner.query(`ALTER TABLE "grupos_itens" DROP CONSTRAINT "FK_b8322a1071ce9ca664dabc80dfa"`);
        await queryRunner.query(`ALTER TABLE "pessoas_gruposItens" DROP CONSTRAINT "FK_4cdd6d219485acd8b9701d076b1"`);
        await queryRunner.query(`ALTER TABLE "pessoas_gruposItens" DROP CONSTRAINT "FK_a60fbcb9bfb12864f6d4fcab008"`);
        await queryRunner.query(`ALTER TABLE "pessoas_gruposItens" DROP CONSTRAINT "FK_cb614ea80ab02c2d6723b2b3e47"`);
        await queryRunner.query(`ALTER TABLE "pessoas" DROP CONSTRAINT "FK_f03548a8d1f8f5cf4d9047a54f6"`);
        await queryRunner.query(`ALTER TABLE "pessoas" DROP CONSTRAINT "FK_3298b8a7e21b647c78c4ade81b1"`);
        await queryRunner.query(`ALTER TABLE "pessoas" DROP CONSTRAINT "FK_0ca7ffcf041c35b7bf80158a06b"`);
        await queryRunner.query(`ALTER TABLE "pessoas" DROP CONSTRAINT "FK_e0aaffbb814e6626ca5cff60560"`);
        await queryRunner.query(`ALTER TABLE "pessoas" DROP CONSTRAINT "FK_66f04e713618358aa6e14b86558"`);
        await queryRunner.query(`ALTER TABLE "notificacoes_usuarios" DROP CONSTRAINT "FK_335d31ebbefc95359a676c6d73a"`);
        await queryRunner.query(`ALTER TABLE "notificacoes_usuarios" DROP CONSTRAINT "FK_eb2e9c866126eefcb0f2890fc82"`);
        await queryRunner.query(`ALTER TABLE "notificacoes" DROP CONSTRAINT "FK_10ec8f8dbe153d521b3b4521faf"`);
        await queryRunner.query(`ALTER TABLE "convites" DROP CONSTRAINT "FK_1673fcbe51386bcab8ec8a0fba1"`);
        await queryRunner.query(`ALTER TABLE "convites" DROP CONSTRAINT "FK_38b065a3191e800ab09ee95be8d"`);
        await queryRunner.query(`ALTER TABLE "produtos" DROP CONSTRAINT "FK_89f6a0d2f5c0e9d9173b9eb955a"`);
        await queryRunner.query(`ALTER TABLE "produtos" DROP CONSTRAINT "FK_afe3324a3eebac3e0cdc0c3d6ff"`);
        await queryRunner.query(`ALTER TABLE "produtos" DROP CONSTRAINT "FK_ff008aca54cdbfccdede506efb3"`);
        await queryRunner.query(`ALTER TABLE "produtos" DROP CONSTRAINT "FK_0546b77e9b78f15ec796e9a19a0"`);
        await queryRunner.query(`ALTER TABLE "cotacoes_itens" DROP CONSTRAINT "FK_40ccc6ee4efabb23b8ebf2107ba"`);
        await queryRunner.query(`ALTER TABLE "cotacoes_itens" DROP CONSTRAINT "FK_4112991f9adb5bfce11a41be73a"`);
        await queryRunner.query(`ALTER TABLE "cotacoes_itens" DROP CONSTRAINT "FK_ae1ca98a176bb6305865bcfe38a"`);
        await queryRunner.query(`ALTER TABLE "cotacoes_itens" DROP CONSTRAINT "FK_281e2dc2af30175924be6ea4804"`);
        await queryRunner.query(`ALTER TABLE "cotacoes_itens_respostas" DROP CONSTRAINT "FK_819a4ee774a78ee75be129eeab5"`);
        await queryRunner.query(`ALTER TABLE "cotacoes_itens_respostas" DROP CONSTRAINT "FK_6f13beb9426cbfc0ef8274d6520"`);
        await queryRunner.query(`ALTER TABLE "cotacoes_itens_respostas" DROP CONSTRAINT "FK_e38bfbe4d671010e25238656eb8"`);
        await queryRunner.query(`ALTER TABLE "cotacoes_itens_respostas" DROP CONSTRAINT "FK_6e4ee75031b19bd7f89b4102c1c"`);
        await queryRunner.query(`ALTER TABLE "cotacoes" DROP CONSTRAINT "FK_c6877b6157ba08b668c85b5ac97"`);
        await queryRunner.query(`ALTER TABLE "cotacoes" DROP CONSTRAINT "FK_6c0a49336f9ec8897fe1708e286"`);
        await queryRunner.query(`ALTER TABLE "cotacoes" DROP CONSTRAINT "FK_01268433833920f1f5f2ba81416"`);
        await queryRunner.query(`ALTER TABLE "cotacoes" DROP CONSTRAINT "FK_465e0759e2b62462b5998418e0a"`);
        await queryRunner.query(`ALTER TABLE "cotacoes" DROP CONSTRAINT "FK_6c2941959b8a5efd0f450155d70"`);
        await queryRunner.query(`ALTER TABLE "cotacoes" DROP CONSTRAINT "FK_267259bd9339d126cd04b036a2c"`);
        await queryRunner.query(`ALTER TABLE "cotacoes" DROP CONSTRAINT "FK_7e6f6b6f92c4c0798a769bd47bf"`);
        await queryRunner.query(`ALTER TABLE "pedidos" DROP CONSTRAINT "FK_11eee576e61da89cf70c92b262b"`);
        await queryRunner.query(`ALTER TABLE "pedidos" DROP CONSTRAINT "FK_5a6aebf7f18aaf59bc342c22fe1"`);
        await queryRunner.query(`ALTER TABLE "pedidos" DROP CONSTRAINT "FK_9a711eef9f3404f0d400ffcf17f"`);
        await queryRunner.query(`ALTER TABLE "pedidos" DROP CONSTRAINT "FK_3a22bd6118266e4492f522dc990"`);
        await queryRunner.query(`ALTER TABLE "pedidos" DROP CONSTRAINT "FK_2e54b204f572dd9cadc48f9fbde"`);
        await queryRunner.query(`ALTER TABLE "pedidos" DROP CONSTRAINT "FK_0db8bbade4d70d9b854cd21e8da"`);
        await queryRunner.query(`ALTER TABLE "pedidos" DROP CONSTRAINT "FK_463ae49639acff27ec8c57f5c73"`);
        await queryRunner.query(`ALTER TABLE "pedidos" DROP CONSTRAINT "FK_2fc639de84f845569ac2c9f78aa"`);
        await queryRunner.query(`ALTER TABLE "pedidos" DROP CONSTRAINT "FK_1f62699d31e9143363438136507"`);
        await queryRunner.query(`ALTER TABLE "pedidos" DROP CONSTRAINT "FK_4818451165ddfea7dee91616b0d"`);
        await queryRunner.query(`ALTER TABLE "pedidos" DROP CONSTRAINT "FK_fc027c56a080c8bb2e00e69923d"`);
        await queryRunner.query(`ALTER TABLE "pedidos" DROP CONSTRAINT "FK_b45a63956a7594764773f78cb39"`);
        await queryRunner.query(`ALTER TABLE "pedidos_parcelas" DROP CONSTRAINT "FK_560fc6fd650396fd26dda2f6c53"`);
        await queryRunner.query(`ALTER TABLE "pedidos_itens" DROP CONSTRAINT "FK_b2f99df3ce1597dceec33cb5e40"`);
        await queryRunner.query(`ALTER TABLE "pedidos_itens" DROP CONSTRAINT "FK_da85f71918d3494bf9594df4385"`);
        await queryRunner.query(`ALTER TABLE "pedidos_itens" DROP CONSTRAINT "FK_2f706fb8997d3e31261fefb653e"`);
        await queryRunner.query(`ALTER TABLE "pedidos_itens" DROP CONSTRAINT "FK_33fe47da4aced52ceec02ff23c5"`);
        await queryRunner.query(`ALTER TABLE "cotacoes_respostas" DROP CONSTRAINT "FK_02cd42b7d9af5310d1d94fb03b7"`);
        await queryRunner.query(`ALTER TABLE "cotacoes_respostas" DROP CONSTRAINT "FK_3dc06ff0400db3d536dceafa901"`);
        await queryRunner.query(`ALTER TABLE "cotacoes_respostas" DROP CONSTRAINT "FK_7c527d2cbe405d77668b613f816"`);
        await queryRunner.query(`ALTER TABLE "cotacoes_respostas" DROP CONSTRAINT "FK_aba805afb0af8dbab83cc755a6b"`);
        await queryRunner.query(`ALTER TABLE "cotacoes_respostas" DROP CONSTRAINT "FK_460690825edeb8543e3918f2d8d"`);
        await queryRunner.query(`ALTER TABLE "cotacoes_respostas_parcelas" DROP CONSTRAINT "FK_c18212ad09a8f6511273c0ebeb3"`);
        await queryRunner.query(`ALTER TABLE "produtos_grupositens" DROP CONSTRAINT "FK_50b4b62bba97280774e05bed17a"`);
        await queryRunner.query(`ALTER TABLE "produtos_grupositens" DROP CONSTRAINT "FK_1e464f40837ae3247e55cd8ee40"`);
        await queryRunner.query(`ALTER TABLE "pessoas_senhas" DROP CONSTRAINT "FK_2678f294df38daa9f2756f8f40e"`);
        await queryRunner.query(`ALTER TABLE "pessoas_senhas" DROP CONSTRAINT "FK_2c4b00947f27a72cb62320d0ee7"`);
        await queryRunner.query(`ALTER TABLE "pessoas_empresas" DROP CONSTRAINT "FK_67b1615978c3e5cea3b3c44c038"`);
        await queryRunner.query(`ALTER TABLE "pessoas_empresas" DROP CONSTRAINT "FK_a88db58b1bab5a7a228867c06a9"`);
        await queryRunner.query(`ALTER TABLE "pessoas_empresas" DROP CONSTRAINT "FK_809ae66ac48d993054d48e03619"`);
        await queryRunner.query(`ALTER TABLE "pessoas_perfis" DROP CONSTRAINT "FK_da5ec819085280f5ab722d36a3b"`);
        await queryRunner.query(`ALTER TABLE "pessoas_perfis" DROP CONSTRAINT "FK_2ff96a7b6faf812bb8be107fd2b"`);
        await queryRunner.query(`ALTER TABLE "pessoas_perfis" DROP CONSTRAINT "FK_6667b206a341502927b2adcd5db"`);
        await queryRunner.query(`ALTER TABLE "perfis" DROP CONSTRAINT "FK_ba06560556c70175564bc2262db"`);
        await queryRunner.query(`ALTER TABLE "menus_perfis" DROP CONSTRAINT "FK_305025e18e469a7dca82ad4f833"`);
        await queryRunner.query(`ALTER TABLE "menus_perfis" DROP CONSTRAINT "FK_09c2491bd9ce41c40545b6652a4"`);
        await queryRunner.query(`ALTER TABLE "menus_perfis" DROP CONSTRAINT "FK_8e62593a05d8953e4c693d5ef00"`);
        await queryRunner.query(`ALTER TABLE "menus" DROP CONSTRAINT "FK_a9299eaf35545a824cef08810f7"`);
        await queryRunner.query(`ALTER TABLE "menus" DROP CONSTRAINT "FK_14a0c59ecd0f07e8822ff0bb803"`);
        await queryRunner.query(`ALTER TABLE "pessoas_sites" DROP CONSTRAINT "FK_bad59387fc1c3ada1273c938a82"`);
        await queryRunner.query(`ALTER TABLE "pessoas_emails" DROP CONSTRAINT "FK_856668b4cd963ce125d6cc6aee8"`);
        await queryRunner.query(`ALTER TABLE "pessoas_telefones" DROP CONSTRAINT "FK_6cae8173f2f12a61a8e05eab978"`);
        await queryRunner.query(`ALTER TABLE "pessoas_telefones" DROP CONSTRAINT "FK_15df92a33de336585e42ea9475a"`);
        await queryRunner.query(`ALTER TABLE "pessoas_telefones" DROP CONSTRAINT "FK_70cee935d4a5ec80e63c8df680c"`);
        await queryRunner.query(`ALTER TABLE "pessoas_enderecos" DROP CONSTRAINT "FK_111a394d4702e247ca8982ef6c5"`);
        await queryRunner.query(`ALTER TABLE "pessoas_enderecos" DROP CONSTRAINT "FK_ba9e3b79db386b895b2430f24bd"`);
        await queryRunner.query(`ALTER TABLE "pessoas_enderecos" DROP CONSTRAINT "FK_dc762ba53b91f0183500f6003e0"`);
        await queryRunner.query(`ALTER TABLE "pessoas_enderecos" DROP CONSTRAINT "FK_c79b8dbdc4ae436013fb73984d4"`);
        await queryRunner.query(`ALTER TABLE "estados" DROP CONSTRAINT "FK_96cad596c2475bddd1b438c16fb"`);
        await queryRunner.query(`ALTER TABLE "estados" DROP CONSTRAINT "FK_e8220b3fcc4dbddf7527705e576"`);
        await queryRunner.query(`ALTER TABLE "cidades" DROP CONSTRAINT "FK_2e7d637be70af707d91216a1933"`);
        await queryRunner.query(`ALTER TABLE "cidades" DROP CONSTRAINT "FK_611ba55ce58e5a520cfc515169f"`);
        await queryRunner.query(`ALTER TABLE "regioes" DROP CONSTRAINT "FK_96248315e0216e821892da6f622"`);
        await queryRunner.query(`ALTER TABLE "pessoas_documentos" DROP CONSTRAINT "FK_29edfe7bdc144184d9d7b269d61"`);
        await queryRunner.query(`ALTER TABLE "pessoas_documentos" DROP CONSTRAINT "FK_b33f3db9e3595ae5794bc84bc4a"`);
        await queryRunner.query(`ALTER TABLE "pessoas_documentos" DROP CONSTRAINT "FK_e939f9735ce931a96cc07a4f7a5"`);
        await queryRunner.query(`ALTER TABLE "eventos" DROP CONSTRAINT "FK_789a59a9e2a08992a9b254e6014"`);
        await queryRunner.query(`ALTER TABLE "eventos" DROP CONSTRAINT "FK_46a0309574009ae28af91f37636"`);
        await queryRunner.query(`DROP TABLE "status"`);
        await queryRunner.query(`DROP TABLE "artigos"`);
        await queryRunner.query(`DROP TABLE "tipos"`);
        await queryRunner.query(`DROP TABLE "tipos_itens"`);
        await queryRunner.query(`DROP TABLE "anexos"`);
        await queryRunner.query(`DROP TABLE "grupos"`);
        await queryRunner.query(`DROP TABLE "grupos_itens"`);
        await queryRunner.query(`DROP TABLE "pessoas_gruposItens"`);
        await queryRunner.query(`DROP TABLE "pessoas"`);
        await queryRunner.query(`DROP TABLE "notificacoes_usuarios"`);
        await queryRunner.query(`DROP TABLE "notificacoes"`);
        await queryRunner.query(`DROP TABLE "convites"`);
        await queryRunner.query(`DROP TABLE "produtos"`);
        await queryRunner.query(`DROP TABLE "cotacoes_itens"`);
        await queryRunner.query(`DROP TABLE "cotacoes_itens_respostas"`);
        await queryRunner.query(`DROP TABLE "cotacoes"`);
        await queryRunner.query(`DROP TABLE "pedidos"`);
        await queryRunner.query(`DROP TABLE "pedidos_parcelas"`);
        await queryRunner.query(`DROP TABLE "pedidos_itens"`);
        await queryRunner.query(`DROP TABLE "cotacoes_respostas"`);
        await queryRunner.query(`DROP TABLE "cotacoes_respostas_parcelas"`);
        await queryRunner.query(`DROP TABLE "produtos_grupositens"`);
        await queryRunner.query(`DROP TABLE "pessoas_senhas"`);
        await queryRunner.query(`DROP TABLE "pessoas_empresas"`);
        await queryRunner.query(`DROP TABLE "pessoas_perfis"`);
        await queryRunner.query(`DROP TABLE "perfis"`);
        await queryRunner.query(`DROP TABLE "menus_perfis"`);
        await queryRunner.query(`DROP TABLE "menus"`);
        await queryRunner.query(`DROP TABLE "pessoas_sites"`);
        await queryRunner.query(`DROP TABLE "pessoas_emails"`);
        await queryRunner.query(`DROP TABLE "pessoas_telefones"`);
        await queryRunner.query(`DROP TABLE "pessoas_enderecos"`);
        await queryRunner.query(`DROP TABLE "estados"`);
        await queryRunner.query(`DROP TABLE "cidades"`);
        await queryRunner.query(`DROP TABLE "regioes"`);
        await queryRunner.query(`DROP TABLE "pessoas_documentos"`);
        await queryRunner.query(`DROP TABLE "eventos"`);
    }

}
